### PR TITLE
[Enhancement] Create Issue Templates (#1)

### PR DESCRIPTION
**Pull request by kevinmatthes**
I think issue templates would help to keep a better overview about the things an issue is about.

### CODE REVIEW

**Comment by wert007** [comment]
I feel like this would hinder people more from actually opening an issue. It makes it a lot more work involved, then it currently is. So I think I oppose this in general for this repo. 😅

**Comment by wert007** [comment]
Hmm, idk, I think it is easier, and also less formal, to just talk about bugs without any forms at all. There is nothing wrong with talking to people basically 😄

**Comment by kevinmatthes** [comment]
How about headlines in the Bug Report template to give an idea about which information are required to work on the issues effectively?

**Comment by kevinmatthes** [comment]
Indeed, the overhead of both issue templates and forms would be too much for the current size of the project.

**Pull request closed without merging**
